apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo-pods
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          volumeMounts:
            - name: mongo-storage # This name should match the volumes name
              mountPath: /data/db # This is the default data directory for MongoDB
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      volumes:
        - name: mongo-storage # This name should match the volumeMounts name
          persistentVolumeClaim:
            claimName: mongo-pvc # This should match the name of your PVC
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  selector:
    app: mongo # This label should match the labels in the pod or deployment
  ports:
    - port: 27017 # Port on the service
      targetPort: 27017 # Port on the pod/container
