apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: todo.com
      http:
        paths:
          - path: /api/ # Match /api and anything after it
            pathType: Prefix
            backend:
              service:
                name: server-service # Name of the service to route to
                port:
                  number: 80
          - path: /?(.*) # Regex to match root and any subpath
            pathType: ImplementationSpecific
            backend:
              service:
                name: client-service # Name of the service to route to
                port:
                  number: 80
